### ISSUE TITLE
Installation instructions needs to be updated

### ISSUE THREAD

**Issue by thisiskaransgit** [meshery/meshery.io#1279] opened 2023-07-10 22:25 UTC
#### Current State of the Meshery.io site
Under the getting started section, the steps mentioned to install Meshery on various platforms haven't been updated.
#### Desired State of the Meshery.io site
- The Commands need to be updated with the reference to installation instructions provided in Meshery docs.

1. Commands for Docker and Kubernetes are utilizing mesheryctl by creating a new platform context
**Example**:  
 `mesheryctl system context create docker --platform docker --set `. and `mesheryctl system start`
This should be changed to use the curl command and download directly package
**Example**: 
 `curl -L https://meshery.io/install | PLATFORM=kubernetes bash - `, 
 We are practicing it under installation through bash but not in the concerned section.

2. Under KinD installation removing the option of using manifest for installation

3. update the GKE installation command to include --token flag, for automatic configuration (one-line instruction on how to get the token will be helpful)
- The link to directly download the CLI manifest, should be removed.

Link: https://docs.meshery.io/installation

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment] 2023-07-10 22:34
@thisiskaransgit thanks much. This is great. I have a request to consider. So as to avoid mishaps, could we first qualify that what is in the Meshery Docs is accurate (that it isn't about of date), and second, identify specifically which instructions on meshery.io are out of date?

**Comment by ranjanmangla1** [comment] 2023-07-11 04:51
I would love to work on it , already working on the same issue for layer5.io

**Comment by Ghat0tkach** [comment] 2023-07-11 06:28
I have ran out of assigned issues for the meshery website 😆 . I would love to take this issue 👀.

**Comment by thisiskaransgit** [comment] 2023-07-14 18:25
> @thisiskaransgit thanks much. This is great. I have a request to consider. So as to avoid mishaps, could we first qualify that what is in the Meshery Docs is accurate (that it isn't about of date), and second, identify specifically which instructions on meshery.io are out of date?

@leecalcote 
I've confirmed the accuracy of installation instructions for all platforms, except for cloud providers.
Meshery.io installation commands need to be updated in terms of using the easiest ways of installation
1. Commands for Docker and Kubernetes are utilizing mesheryctl by creating a new platform context
**Example**:  
 `mesheryctl system context create docker --platform docker --set `. and `mesheryctl system start`
This should be changed to use the curl command and download directly package
**Example**: 
 `curl -L https://meshery.io/install | PLATFORM=kubernetes bash - `, 
 We are practicing it under installation through bash but not in the concerned section.

2. Under KinD installation removing the option of using manifest for installation

3. update the GKE installation command to include --token flag, for automatic configuration (one-line instruction on how to get the token will be helpful)

I think we can move ahead to update the meshery.io website.

In Documentation:
- There are no immediate updates needed, though there's a scope for improvement in formatting and some future proofing, some parts of the installation can be updated to opt out of using --version flags such as in Helm(for meshery) and minikube(for k8s) as they would install the latest versions by default. 
- Windows installation can be updated as the docker toolbox is out of the story and wsl2 should be appearing first with the simple PowerShell command of `wsl --install`  for installation.

**Comment by ranjanmangla1** [comment] 2023-07-14 18:27
Actually, @Ghat0tkach , I am working on this exact issue, if you don't mind, let me work on this!

**Comment by Cvr421** [comment] 2023-07-17 13:00
Hii @thisiskaransgit  Can I work on this

**Comment by thisiskaransgit** [comment] 2023-07-17 13:51
Assigning it in the chronological order @ranjanmangla1, go ahead with this one. Thank you @Ghat0tkach and @Cvr421 for volunteering though.

**Comment by Cvr421** [comment] 2023-07-17 20:09
No problem @thisiskaransgit 😊

**Comment by Ghat0tkach** [comment] 2023-07-25 08:13
@ranjanmangla1 any updates?

**Comment by thisiskaransgit** [comment] 2023-07-25 21:13
since we haven't heard back from @ranjanmangla1, @Ghat0tkach, kindly take over this issue

**Comment by Ghat0tkach** [comment] 2023-07-26 11:44
Thanks @thisiskaransgit , On my way 🙌

**Comment by Ghat0tkach** [comment] 2023-07-26 16:05
@thisiskaransgit  , as @ranjanmangla1 was unable to access his laptop for the past 10 days due to repairing .I'll reassign him as he assured to complete it by this weekend. 🙌

**Comment by leecalcote** [comment] 2023-07-26 16:12
Folks, there's no shortage is issues to work on - only maintainers to help create them, review and close them.

Given this, there's little need to wait over two weeks for @ranjanmangla1 when during that time we are giving users improper installation instructions. The logic here is backwards.

Let's get this issue completed today. Let me know if this isn't possible and I'll complete it.

**Comment by leecalcote** [comment] 2023-07-26 16:13
This is the sort of small issue, quick to fix, with high user impact that should be handled in the same breath that the issue is opened.

**Comment by Ghat0tkach** [comment] 2023-07-26 16:18
Okay @leecalcote  , I'll complete it by today

**Closed** 2023-08-16 18:51 UTC
Labels: good first issue, help wanted, area/website
