### ISSUE TITLE
[UI] Enhance the styling of the scroll bar

### ISSUE THREAD

**Issue by akash-singh8** [meshery/meshery.io#1067] opened 2023-03-04 06:39 UTC
#### Current Behavior
The default scrollbar in the Edge browser does not meet the desired aesthetic standards, prompting the need to enhance its appearance through appropriate design measures.

#### Desired Behavior
Revamp the scroll bar by implementing a new design that aligns with the aesthetic requirements.

#### Implementation
Incorporate CSS properties for the scroll bar to ensure consistency in appearance across all browsers.

#### Mockups
![image](https://user-images.githubusercontent.com/85285176/222879754-712f8258-50e3-4e73-9027-032e982a774a.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Chadha93** [comment] 2023-03-11 07:02
@akash-singh8 Thank you for opening up this issue, This issue is for the meshery.io site. I've transferred it here.

**Comment by parmishh** [comment] 2023-03-11 07:59
@Chadha93 no one is currently assigned this can I work on it . I have already figured it out.😊

**Comment by ishaan812** [comment] 2023-04-04 19:25
Can I be assigned this?

**Comment by GaganpreetKaurKalsi** [comment] 2023-04-09 20:44
Oh this issue is pretty long pending. Though I haven't tested on edge, I tested on chrome, safari and firefox. The scrollbar is invisible in light mode. Need to adjust it's color for light mode.

@parmishh , @ishaan812 any one of you who's ready to fix this up.

**Comment by parmishh** [comment] 2023-04-10 01:05
@GaganpreetKaurKalsi I would like to work on it. Please Assign it to me.

**Comment by parmishh** [comment] 2023-04-10 04:24
@GaganpreetKaurKalsi can you elaborate more in my device using chrome its visible.
<img width="35" alt="Capture" src="https://user-images.githubusercontent.com/91942072/230825615-3bdce114-749c-4046-8bf7-07da8b4702e0.PNG">

**Comment by GaganpreetKaurKalsi** [comment] 2023-04-10 05:45
> @GaganpreetKaurKalsi can you elaborate more in my device using chrome its visible. <img alt="Capture" width="35" src="https://user-images.githubusercontent.com/91942072/230825615-3bdce114-749c-4046-8bf7-07da8b4702e0.PNG">

Hardware??
On mac chrome, it looks like this in dark-mode and not visible in light mode because of color issues.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/230834723-8c3e8f94-4244-4178-a902-811a59ca7c52.png">

**Comment by parmishh** [comment] 2023-04-10 06:31
Got it, working on it

**Comment by ayesha-firdaus** [comment] 2023-05-06 18:28
Can you assign me this? I am interested

**Comment by 8rxn** [comment] 2023-05-07 05:41
Hey @leecalcote, I think the issue is still unresolved. 
I would like to proceed with this issue.
Can it be assigned to me?

**Comment by Shivam-AfA** [comment] 2023-05-08 09:59
So we can let @ayesha-firdaus try their hand at this. @8rxn can help if the issue still remains unresolved.

@ayesha-firdaus Please create a PR to showcase your ideas regarding the scrollbar and please do mention this issue in the PR.

**Comment by Savio629** [comment] 2023-05-08 10:25
Also to add on, we need someone to fix the visibility of scrollbar on mac.

**Comment by ayesha-firdaus** [comment] 2023-05-16 15:20
actually I have my semester exams and I am a newcomer to open source so it will take time for me understand and set the local environment.

**Comment by Savio629** [comment] 2023-06-04 13:03
@ayesha-firdaus progress?

**Comment by Gautam-666** [comment] 2023-06-06 06:24
I would like to work on this issue if no one is working on it... Thanks

**Comment by shadow0500** [comment] 2023-06-09 11:02
Can I work on this issue ??

**Comment by 8rxn** [comment] 2023-06-09 11:28
Thanks for offering your help here @shadow0500 but @Gautam-666 is taking care of this.

**Comment by shadow0500** [comment] 2023-06-09 11:34
Okay @8rxn  and thank you for the response.

**Closed** 2023-06-25 19:41 UTC
Labels: kind/enhancement, component/ui, language/javascript, framework/react
