### ISSUE TITLE
Menu and hamburger icon not aligned properly in small screens

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1035] opened 2023-02-20 11:27 UTC
### Description

On a small-width screen menu icon and hamburger icon are not aligned properly and there is no need for menu text when there is already a hamburger icon.
### Expected Behavior

There should only be a hamburger icon on small screens and remove menu text.

### Screenshots
![image](https://user-images.githubusercontent.com/90546692/220093727-e85ee851-eb55-4d67-993e-5513ebaa0560.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment] 2023-02-20 11:27
can i work on this issue

**Comment by sudhanshutech** [comment] 2023-02-20 16:49
hey @tinniaru3005 I have created the issue

**Comment by tinniaru3005** [comment] 2023-02-20 16:57
> can i work on this issue

Ya sure.

**Comment by tinniaru3005** [comment] 2023-02-20 16:59
As discussed in the meet, remove the text "menu" and just keep the icon

**Comment by sudhanshutech** [comment] 2023-02-20 17:09
> Expected

yeah sure

**Comment by sudhanshutech** [comment] 2023-02-23 12:22
@tinniaru3005 the issue I am working on is not visible on my development server 
![image](https://user-images.githubusercontent.com/90546692/220903849-a91857be-6a0b-4027-b704-69ed1e055db2.png)
![image](https://user-images.githubusercontent.com/90546692/220903936-215d301f-63ab-49ff-a9d0-7ca1268748f1.png)
but in the live server
![image](https://user-images.githubusercontent.com/90546692/220904152-bfe35eab-758b-4231-a200-e5c7f5e143be.png)
![image](https://user-images.githubusercontent.com/90546692/220904319-93a4bb30-a546-4fe5-affd-cc70499539d0.png)

**Comment by sudhanshutech** [comment] 2023-02-23 13:51
> Hey @sudhanshutech, have you synced all the latest commits?

Yes, I have updated the branch. I have tried through gitpod also but there also this issue is not visible

**Comment by sudhanshutech** [comment] 2023-02-23 13:52
@tinniaru3005 could it be due to any browser compatibility?

**Comment by tinniaru3005** [comment] 2023-02-23 14:02
Hey @sudhanshutech, I checked it. Even I am facing the same issue. @Chadha93 can you please help us with it.

**Comment by tinniaru3005** [comment] 2023-03-07 06:23
@sudhanshutech any update on the progress of the issue?

**Comment by sudhanshutech** [comment] 2023-03-07 06:40
> @sudhanshutech any update on the progress of the issue?

As I mentioned, the issue is not visible on my development server, so I could not solve it. But I'll go through once more and let you know

**Comment by randychilau** [comment] 2023-03-27 22:58
Good day.

This issue was mentioned on a recent call which made me curious to take a look.

From reviewing the code, It seems that the issue may be caused by [environment conditionals in Jekyll](https://jekyllrb.com/docs/configuration/environments/) and this part of the code in the following file could be the reason: 

_includes/footer.html

![image](https://user-images.githubusercontent.com/90356410/228074220-6bb07898-590c-4d79-b8fa-84051b8f66dc.png)

If it is [specified "production"](https://jekyllrb.com/docs/step-by-step/10-deployment/) in the serve (or build) command:

JEKYLL_ENV=production bundle exec jekyll serve

the code uses the file "/stellarnav.min.js" (which has a menuLabel variable set to "Menu") to build the site:
![image](https://user-images.githubusercontent.com/90356410/228081089-9b8efe23-d5e8-4453-8e45-32c0b9544c01.png)

if "development" is specified:

JEKYLL_ENV=development bundle exec jekyll serve

the code uses the file "/js/stellarnav.js", (which had "Menu" removed and other code [changes in this commit](https://github.com/meshery/meshery.io/commit/31817d78f515e70b7c81432ac108b61c3afc433e)) to build the site:
![image](https://user-images.githubusercontent.com/90356410/228080932-dd91fa87-f064-453f-8f74-41f971a1dd0e.png)

-----

If the JEKYLL_ENV key was set to "production" for the jekyll build to generate the site for production, then that may be why the "Menu" text is appearing.

One possible approach would be to remove the highlighted text from the "/stellarnav.min.js" file which is being used by "production":

![image](https://user-images.githubusercontent.com/90356410/228076067-96d4078d-8ec1-4cba-b53f-3c18231e6e0b.png)

Or another approach would be to modify the environment conditional in the footer.html file mentioned above so that it uses the "/js/stellarnav.js" file instead of the "/stellarnav.min.js" file.

Hopefully that information is helpful.

Cheers,
Randy

**Comment by Savio629** [comment] 2023-04-23 05:18
@sudhanshutech This issue has been solved in this pr - #1130 
So you can close this issue.

**Closed** 2023-04-23 09:21 UTC
Labels: kind/bug
