### ISSUE TITLE
[Grammar Adjustment] Learn - Frequently Asked Questions

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery.io#1424] opened 2023-09-15 12:16 UTC
**Current State:**

- Link to website: https://play.meshery.io/#signup-form
- Currently, the text in the 5th question reads as follows: "Are designs that I create in the Meshery Playground saved or will I look any work that I do in the playground?"

**Desired State:**

- The suggested change is to adjust the text so it reads: "Are designs that I create in the Meshery Playground saved or will I lose any work that I do in the playground?"

---
**Screenshot**

![mesh](https://github.com/layer5io/layer5/assets/19821445/3ab08b2b-85e7-4993-9f62-00a7812a19df)

**Comment by hemantmm** [comment] 2023-09-15 16:23
Hi, @sandramsc can I resolve this issue?

**Comment by sandramsc** [comment] 2023-09-15 16:42
> Hi, @sandramsc can I resolve this issue?

CC: @abhijeetgauravm

Thank you for your interest in working on this issue! Its transferred from a different repo, and is already assigned to @PRANJALRANA11 (still might need to ask for re-assignment if interested)

**Comment by abhijeetgauravm** [comment] 2023-09-15 19:26
> > Hi, @sandramsc can I resolve this issue?
> 
> CC: @abhijeetgauravm
> 
> Thank you for your interest in working on this issue! Its transferred from a different repo, and is already assigned to @PRANJALRANA11 (still might need to ask for re-assignment if interested)

@Ghat0tkach @Mohith234 Can u assign him?

**Comment by Krutikaa04** [comment] 2023-09-18 04:48
hii @sandramsc  , if the issue isn't resolved yet, will you pls assign it to me!?

**Closed** 2023-11-04 17:59 UTC
Labels: kind/bug
