### ISSUE TITLE
Add spacing between newsletter form and discussion points

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [meshery/meshery.io#1674] opened 2024-03-27 09:59 UTC
### Current Behavior
On https://meshery.io/programs page and in the last section there is no spacing between the form and discussion points which is making UI a bit rough

### Desired Behavior
There should be some spacing between them.

### Screenshots / Mockups
![Screenshot from 2024-03-27 14-53-49](https://github.com/meshery/meshery.io/assets/54661456/305dc61f-017a-4fe8-a2e7-5487a854a7b7)

Thank you.
---
<img src="https://raw.githubusercontent.com/meshery/meshery.io/master/assets/images/logos/meshery-logo.png" width="16px" align="left" /><h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by TheOjasSingh** [comment] 2024-03-28 14:12
@Muhammed-Moinuddin Can you assign me this issue

**Comment by Muhammed-Moinuddin** [comment] 2024-03-28 14:21
> @Muhammed-Moinuddin Can you assign me this issue

I cannot assign but I'm not working on it so you can.

**Comment by leecalcote** [comment] 2024-03-28 22:01
Thanks for raising this issue. 👍

**Comment by ShivamAhir** [comment] 2024-03-29 18:23
it is looking good on my browser

<img width="1403" alt="Screenshot 2024-03-29 at 11 50 24 PM" src="https://github.com/meshery/meshery.io/assets/74092725/cd2a5086-879d-4d33-bedd-4058dc0978b4">

**Comment by TheOjasSingh** [comment] 2024-04-02 03:57
I think someone else has already fixed this issue

**Comment by TheOjasSingh** [comment] 2024-04-02 03:58
@leecalcote please close this issue

**Comment by sudhanshutech** [comment] 2024-04-04 16:51
Thanks @TheOjasSingh @ShivamAhir to jump here. The issue is already completed so lets close this.

**Closed by sudhanshutech** 2024-04-04 16:51 UTC
Labels: kind/enhancement, area/website
