### ISSUE TITLE
Button Covered by Image - UI Bug

### ISSUE THREAD

**Issue by rahulrana701** [meshery/meshery.io#1822] opened 2024-07-13 09:52 UTC
### Description
There is a UI issue where an image is covering a button on screens below 767px  which should not be the case . Notably, this issue does not occur with any other buttons throughout the website except this section.
### Screenshots
![Screenshot 2024-07-13 124603](https://github.com/user-attachments/assets/72234bd2-bc8b-4702-b9df-45c47c3fc13f)

### Expected Behavior
The button should be fully visible, not covered by any images , on screens below 767px.
![Screenshot 2024-07-13 152131](https://github.com/user-attachments/assets/f778fd36-e875-4216-a9ed-1b78a9acc1cf)

### Reproduce bug
Go to the browser 
Go to inspect 
Check the website home page on screen below 767px and check get snapshots of your infrastructure directly in your PRs section.

### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by rahulrana701** [comment] 2024-07-13 09:55
I would like to work on this issue

**Comment by Ashparshp** [comment] 2024-07-15 07:09
@rahulrana701,
Thank you for addressing this issue! But before proceeding, could you please get assigned to the issue? Additionally, could you provide detailed steps to reproduce the issue? It would also be helpful to include a link or URL where we can view the affected section....

Thanks for your contributions!

**Comment by rahulrana701** [comment] 2024-07-15 11:58
> @rahulrana701,
> 
> Thank you for addressing this issue! But before proceeding, could you please get assigned to the issue? Additionally, could you provide detailed steps to reproduce the issue? It would also be helpful to include a link or URL where we can view the affected section....
> 
> 
> 
> Thanks for your contributions but please follow and read the contribution guidelines!!

Sure I will definitely keep this in mind from now on

**Comment by amitamrutiya** [comment] 2024-08-16 03:51
@Ashparshp This can be closed because my PR #1855 has been merged.

**Comment by Ashparshp** [comment] 2024-08-16 03:58
@amitamrutiya Good Good..

**Closed by Ashparshp** 2024-08-16 03:57 UTC
Labels: kind/bug
