### ISSUE TITLE
[Bug] Broken link in footer

### ISSUE THREAD

**Issue by YashKamboj** [meshery/meshery.io#698] opened 2022-04-23 14:49 UTC
**Description**
A brief description of the issue.
Link for blog in footer is broken in meshery.io.
**Expected Behavior**
Remove "/" from the end of the link
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Akshit42-hue** [comment] 2022-04-23 14:51
Can I work on this issue @YashKamboj

**Comment by YashKamboj** [comment] 2022-04-23 14:52
@Akshit42-hue Go Ahead!!!

**Comment by bhargavmungara** [comment] 2022-04-23 16:45
@YashKamboj  I fixed the issue can tell what is the process of submitting  PR

**Comment by Akshit42-hue** [comment] 2022-04-24 18:07
Hey @bhargavmungara, the procedure for contributing is first ask the maintainer to assigned the issue to you or the step how you can resolve the issue after the issue is assigned to you have to raise a pr. If you have any question feel free to ask on slack :)

**Comment by Akshit42-hue** [comment] 2022-04-28 04:15
Hey @bhargavmungara are you working on this issue or should I go ahead

**Comment by YashKamboj** [comment] 2022-04-29 09:56
@bhargavmungara while adding the files, just add the ones you have changed 
eg: git add <files path>

**Comment by Akshit42-hue** [comment] 2022-04-29 10:17
Hey @bhargavmungara, you can refer this  [Docs](https://docs.pi-hole.net/guides/github/how-to-signoff/) for process of signing the DCO

**Comment by leecalcote** [comment] 2022-04-29 11:25
Thank you, @Akshit42-hue

**Closed** 2022-05-02 10:28 UTC
Labels: kind/bug, good first issue
