### ISSUE TITLE
Dark Mode Button Slightly Lifted in Navbar

### ISSUE THREAD

**Issue by VivekBaldha0712** [meshery/meshery.io#1422] opened 2023-09-14 07:28 UTC
### Description
In the current state of our web application, I have noticed an issue with the dark mode button's positioning within the navbar. The dark mode button, which should be flush with the navbar background, appears to be slightly elevated or misaligned

### Expected Behavior
The dark mode button should seamlessly integrate into the navbar, aligning perfectly with the background and maintaining a cohesive design.

### Screenshots
<img width="958" alt="Screenshot 2023-09-14 125002" src="https://github.com/meshery/meshery.io/assets/86009821/1c89e3c1-1b3c-4356-a518-e03327641f31">

### Enviroment:
 - OS: Windows
 - Browser: Chrome
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by VivekBaldha0712** [comment] 2023-09-14 07:29
I would like to work on this issue.

**Comment by Adi-ty** [comment] 2023-09-14 22:53
Refer to the issue #1386 It is already open issue.

**Comment by Mohith234** [comment] 2023-09-16 09:55
I'm closing this issue as it is a duplicate of #1386

Thanks for your contribution @VivekBaldha0712 @Adi-ty

**Closed by Mohith234** 2023-09-16 09:55 UTC
Labels: kind/bug
